### ISSUE TITLE
nova won't load

### ISSUE THREAD

**Issue by northyrn** [kuiperdog/nova#12]
ever since nova went down a bit ago, nothing on nova will load. it's just perpetually the loading symbol.

**Comment by kuiperdog** [comment]
Hello, could you provide a link of a Nova page which is affected, and let me know which browser you're using?

**Comment by northyrn** [comment]
> Hello, could you provide a link of Nova page which is affected, and let me know which browser you're using?

it's all pages! anything at all. i use the nova.nakko.fans link

**Comment by kuiperdog** [comment]
The only official instance of Nova is available at https://nova.gd - I cannot provide support for other instances as I do not have any affiliation with their management or their maintenance.
