### ISSUE TITLE
update the back on c325 + add s21-s24 categories as they're coming soon

### ISSUE THREAD

**Issue by crystalmirror** [kuiperdog/nova#9]
s21's c325's back image was glitched but they updated it soon after. however it's still glitched on nova
also add s21-s24 categories because the only way to view their c325 now is on the home page

**Comment by crystalmirror** [comment]
also could you add an indicator for duplicate objekts?

**Comment by kuiperdog** [comment]
The database has been resynced, so all faulty Objekts should now display properly. Member filters are determined by Cosmo, not by Nova.
